### ISSUE TITLE
(URGENT) Use official W3C API for data fetching

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#44]
From:
* https://github.com/ietf-tools/relaton-data-w3c/issues/18

The `tr.rdf` has finally completely disappeared due to service discontinuance.

We need to use the official W3C API for data fetching at https://api.w3c.org.

**Comment by andrew2net** [comment]
As discussed with @ronaldtse the API gives as
```yaml
$ w3c_api specification fetch --shortname=webrtc --format=yaml
---
shortlink: https://www.w3.org/TR/webrtc/
description: "<p>This document defines a set of ECMAScript APIs in WebIDL to allow
  media to be sent to and received from another browser or device implementing the
  appropriate set of real-time protocols. This specification is being developed in
  conjunction with a protocol specification developed by the IETF RTCWEB group and
  an API specification to get access to local media devices.</p>"
title: 'WebRTC: Real-Time Communication in Browsers'
shortname: webrtc
editor_draft: https://w3c.github.io/webrtc-pc/
series_version: '1.0'
_links:
  self:
    href: https://api.w3.org/specifications/webrtc
  version_history:
    href: https://api.w3.org/specifications/webrtc/versions
  first_version:
    href: https://api.w3.org/specifications/webrtc/versions/20111027
    title: Working Draft
  latest_version:
    href: https://api.w3.org/specifications/webrtc/versions/20241008
    title: Recommendation
  series:
    href: https://api.w3.org/specification-series/webrtc
```
From the response we can obtain
-  shortlink => source
- description = > abstract
- title => title
- shortname => ID
- series_version => series/number
- version_history => relations
- TR from the shortlink => doctype (technicalReport)

For versioned documents the API additionaly provides
```yaml
$ w3c_api specification fetch --shortname=webrtc --version=20111027
---
status: Working Draft
rec_track: true
editor_draft: https://w3c.github.io/webrtc-pc/
uri: https://www.w3.org/TR/2011/WD-webrtc-20111027/
date: '2011-10-27T00:00:00+00:00'
informative: false
title: 'WebRTC 1.0: Real-time Communication Between Browsers'
shortlink: https://www.w3.org/TR/webrtc/
_links:
  self:
    href: https://api.w3.org/specifications/webrtc/versions/20111027
  specification:
    href: https://api.w3.org/specifications/webrtc
```
- status
  - Working Draft => W3C WD {ID}
  - Recommendation => W3C REC {ID}
- date => date[@type="published"]

The https://api.w3.org/doc also has “editors” and “deliverers” endpoints but I didn't fid such functionality in the https://github.com/relaton/w3c_api gem. @ronaldtse  should I implement fetching “editors” and “deliverers” in w3c_api?

**Comment by ronaldtse** [comment]
@andrew2net yes I think we should implement it. I think my approach to this gem was incorrect...

Technically what we want is to recursively fetch these objects according to the links, i.e.

If we consider that these are unrealized links:
```yaml
  xxx:
    href: https://api.w3.org/specifications/webrtc/versions/20111027
    title: Working Draft
```

1. Find all specifications (which are "unrealized" links)
2. For each unrealized link, we need to fetch it and cast it using the right model. The means we have to deduce the model from the URL given. 
3. From a Link model, we have something called `link#realize` which will fetch that model. Maybe polymorphic models?
4. Then we recursively call `realize` on a specific set of links (e.g. we want `specification` but not `self`) of the model. Then those are chained together.

This is relevant to a JSON-LD approach... I'm not entirely sure how to best handle it.
